# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cloudpush < Formula
  desc "Cloudpush's official cli tool"
  homepage "https://portal.cloudpushdev.com/"
  version "0.0.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/cloudpushdev/releases/releases/download/0.0.0/cloudpush_Darwin_x86_64.tar.gz"
      sha256 "7429a83a0b70a8b2abb36035d90bbfe3e7c677971b20c3a51a37b985b44995f4"

      def install
        bin.install "cloudpush"
      end
    end
    on_arm do
      url "https://github.com/cloudpushdev/releases/releases/download/0.0.0/cloudpush_Darwin_arm64.tar.gz"
      sha256 "118ec27ad07bed3fa157d7c7f56b576d3336198fb7c5bab062cb21df5ee39817"

      def install
        bin.install "cloudpush"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cloudpushdev/releases/releases/download/0.0.0/cloudpush_Linux_x86_64.tar.gz"
        sha256 "ea75e66d386e717f85967afd2ef5de78dffd641e66e1f1c8a492d2bb35db5975"

        def install
          bin.install "cloudpush"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cloudpushdev/releases/releases/download/0.0.0/cloudpush_Linux_arm64.tar.gz"
        sha256 "11cf5c419b1e094343087168b9d6b2e83d6b62466d98f08667caca190927614d"

        def install
          bin.install "cloudpush"
        end
      end
    end
  end
end
