# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cloudpush < Formula
  desc "Cloudpush's official cli tool"
  homepage "https://portal.cloudpushdev.com/"
  version "0.0.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/cloudpushdev/releases/releases/download/0.0.0/cloudpush_Darwin_x86_64.tar.gz"
      sha256 "1adc892c813406206942d789b7afa0a42002d10e1bd70523826d3dc733ebf7d5"

      def install
        bin.install "cloudpush"
      end
    end
    on_arm do
      url "https://github.com/cloudpushdev/releases/releases/download/0.0.0/cloudpush_Darwin_arm64.tar.gz"
      sha256 "e5b7527893958e3cbb017a36739aef88a975eaa929d16809efb0238da8d6d6a4"

      def install
        bin.install "cloudpush"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cloudpushdev/releases/releases/download/0.0.0/cloudpush_Linux_x86_64.tar.gz"
        sha256 "7eb70bb137f138d36c69b9aa3e783408b8439a057810cfa2f6fa13f81f3b6d00"

        def install
          bin.install "cloudpush"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/cloudpushdev/releases/releases/download/0.0.0/cloudpush_Linux_armv6.tar.gz"
        sha256 "240b56fd958d1cc7ccc396bfb6ec73a6230170566342e3026c103de4af58b93a"

        def install
          bin.install "cloudpush"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cloudpushdev/releases/releases/download/0.0.0/cloudpush_Linux_arm64.tar.gz"
        sha256 "2da7f1ebff4afd57509436448bf9d614f14f145121d21052086958414bb76536"

        def install
          bin.install "cloudpush"
        end
      end
    end
  end
end
