# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cloudpush < Formula
  desc "Cloudpush's official cli tool"
  homepage "https://portal.cloudpushdev.com/"
  version "0.0.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/cloudpushdev/releases/releases/download/0.0.0/cloudpush_Darwin_x86_64.tar.gz"
      sha256 "03ab02514c4757632c6cd860da18b0de7c360499dc0e4f59bd3d061e5497cebf"

      def install
        bin.install "cloudpush"
      end
    end
    on_arm do
      url "https://github.com/cloudpushdev/releases/releases/download/0.0.0/cloudpush_Darwin_arm64.tar.gz"
      sha256 "ccbd3d2c9ed581c1ca7879e6e9ffe3d4cb40dc44ddabb3cea42039827c4027f4"

      def install
        bin.install "cloudpush"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cloudpushdev/releases/releases/download/0.0.0/cloudpush_Linux_x86_64.tar.gz"
        sha256 "97ce612f5039ef760c6d2db49a7e69a8dbc73bc9a074dfc099db43efefa89fb2"

        def install
          bin.install "cloudpush"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/cloudpushdev/releases/releases/download/0.0.0/cloudpush_Linux_armv6.tar.gz"
        sha256 "808c17d51be34ea0761c826c5869e8e83c06df529dd2fa59566d4f13fe29a5c5"

        def install
          bin.install "cloudpush"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cloudpushdev/releases/releases/download/0.0.0/cloudpush_Linux_arm64.tar.gz"
        sha256 "d43d814ca08ebfaa332557259c6cf4a45fa573421dcc940fcd8f220ae4cede96"

        def install
          bin.install "cloudpush"
        end
      end
    end
  end
end
